### ISSUE TITLE
ModuleNotFoundError when loading plugin

### ISSUE THREAD

**Issue by MaxGodTier** [vltmedia/QuickMocap-BlenderAddon#1]
Out of the box, if I install the plugin from the .zip package directly in Blender it will throw this error:
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'QuickMocap-BlenderAddon-0'
```
Just by renaming the `C:\Users\...\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\QuickMocap-BlenderAddon-0.3.0` folder to something simpler (ie. "quickmocap") will throw a different error:
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Luca\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\QuickMocap-BlenderAddon\__init__.py", line 2, in <module>
    from panels.quickmocap_panel_ImportNMocap import QMOCAP_PT_ImportNMocap
ModuleNotFoundError: No module named 'panels'
```
Restarting Blender as suggested doesn't improve the situation at all, any idea how to make this work? I'm not familiar with Blender.

**Comment by vltmedia** [comment]
Hi, sorry about the frustration, we just fixed the issue, please check out the Release page for a new release!

**Comment by MaxGodTier** [comment]
Tried the new version but I'm still getting this error under Windows 10 and Blender 2.92
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Luca\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\QuickMocap\__init__.py", line 2, in <module>
    from panels.quickmocap_panel_ImportNMocap import QMOCAP_PT_ImportNMocap
ModuleNotFoundError: No module named 'panels'
```

**Comment by vltmedia** [comment]
@MaxGodTier did you download the QuicMocap.zip file from the newest Release? This should be the file you use to install the addon with. Just incase you attempted to install using the Source Files.

We just successfully tested the install on Windows Blender builds : 2.83, 2.91, 2.92, and 3.0a

**Comment by MaxGodTier** [comment]
Yes, I downloaded "QuicMocap.zip" from the newest Release, here's a [video recording of what I'm doing](https://webmshare.com/47X59). Honestly I have no idea why it's happening.

**Comment by vltmedia** [comment]
@MaxGodTier So we just created a new Release with a quick fix for importing the panels module. 

Please attempt the new release, and hopefully this works! Sorry about the problems, and thanks for the video.
We just successfully tested on a remote computer running Blender 2.83  and no environment variables set.
